package commands.artistcmds;

import app.Event;
import app.SingletonAdmin;
import app.user.Artist;
import app.user.User;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import commands.CommandRunner;
import fileio.input.CommandInput;

import java.util.ArrayList;

public final class RemoveEvent implements CommandRunner {

    public RemoveEvent() {

    }

    /**
     * RemoveEvent object node
     *
     * @param commandInput      the input command from the input/test* files
     * @return                  the ouput command, on object node that will be written
     *                          in the files of the result/ directory
     */
    @Override
    public ObjectNode execute(final CommandInput commandInput) {
        String message = removeEventMessage(commandInput);

        ObjectMapper objectMapper = new ObjectMapper();
        ObjectNode objectNode = objectMapper.createObjectNode();

        objectNode.put("command", commandInput.getCommand());
        objectNode.put("user", commandInput.getUsername());
        objectNode.put("timestamp", commandInput.getTimestamp());
        objectNode.put("message", message);

        return objectNode;
    }

    /**
     * RemoveEvent message
     *
     * @param commandInput       from the input/test* files
     * @return                   the message generated by the execution of the input command
     */
    private static String removeEventMessage(final CommandInput commandInput) {
        String username = commandInput.getUsername();

        SingletonAdmin admin = SingletonAdmin.getInstance();
        User user = admin.getUserByName(username);
        admin.setCurrentUser(user);

        if (user == null) {
            return "The username " + username + " doesn't exist.";
        }

        // removing the loaded audio file from the player
        user.anulatesUserLoad();
        user.setTimestampLastPlayedFile(null);


        if (!user.getClass().equals(Artist.class)) {
            return (username + " is not an artist.");
        }

        Artist artist = (Artist) user;      // down-casting from User to Artist
        String name = commandInput.getName();
        Event removedEvent = artist.getEventByName(name);

        if (removedEvent == null) {
            return (username + " doesn't have an event with the given name.");
        }

        // the event can be successfully removed
        ArrayList<Event> events = artist.getEvents();
        events.remove(removedEvent);
        artist.setEvents(events);

        return (username + " deleted the event successfully.");
    }
}
