package commands.playercmds;

import app.SingletonAdmin;
import app.audio.Collections.AudioCollection;
import app.player.Player;
import app.searchBar.SearchBar;
import app.user.User;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import commands.CommandRunner;
import fileio.input.CommandInput;

public final class Load implements CommandRunner {

    public Load() {

    }

    /**
     * Load object node
     *
     * @param commandInput      the input command from the input/test* files
     * @return                  the ouput command, on object node that will be written
     *                          in the files of the result/ directory
     */
    @Override
    public ObjectNode execute(final CommandInput commandInput) {
        String message = loadMessage(commandInput);

        ObjectMapper objectMapper = new ObjectMapper();
        ObjectNode objectNode = objectMapper.createObjectNode();

        objectNode.put("command", commandInput.getCommand());
        objectNode.put("user", commandInput.getUsername());
        objectNode.put("timestamp", commandInput.getTimestamp());
        objectNode.put("message", message);

        return objectNode;
    }

    /**
     * Load message
     *
     * @param commandInput       from the input/test* files
     * @return                   the message generated by the execution of the input command
     */
    public static String loadMessage(final CommandInput commandInput) {
        String username = commandInput.getUsername();

        SingletonAdmin admin = SingletonAdmin.getInstance();
        User user = admin.getUserByName(username);
        admin.setCurrentUser(user);


        if (user == null) {
            return ("The username " + username + " doesn't exist.");
        }

        if (!user.isOnline()) {
            return (username + " is offline.");
        }

        SearchBar searchBar = user.getSearchBar();
        Player player = user.getPlayer();

        if (searchBar.getLastSelectedLibraryEntry() == null) {
            return "Please select a source before attempting to load.";
        }

        if (!searchBar.getLastSearchType().equals("song")
                && ((AudioCollection) searchBar
                .getLastSelectedLibraryEntry()).getNumberOfTracks() == 0) {
            return "You can't load an empty audio collection!";
        }

        // loading the source in the player

        player.setSource(searchBar.getLastSelectedLibraryEntry(), searchBar.getLastSearchType());
        searchBar.clearSelection();

        searchBar.setLoadedLibraryEntry(searchBar.getLastSelectedLibraryEntry());

        player.pause();

        user.setPlayer(player);
        user.setSearchBar(searchBar);
        user.setTimestampLastPlayedFile(commandInput.getTimestamp());

        return "Playback loaded successfully.";
    }

}
