package commands.usercmds;

import app.SingletonAdmin;
import app.user.User;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import commands.CommandRunner;
import fileio.input.CommandInput;

import java.util.ArrayList;

public final class GetOnlineUsers implements CommandRunner {

    public GetOnlineUsers() {

    }

    /**
     * GetOnlineUsers object node
     *
     * @param commandInput      the input command from the input/test* files
     * @return                  the ouput command, on object node that will be written
     *                          in the files of the result/ directory
     */
    @Override
    public ObjectNode execute(final CommandInput commandInput) {
        ArrayList<String> result = getOnlineUsersResult();

        ObjectMapper objectMapper = new ObjectMapper();
        ObjectNode objectNode = objectMapper.createObjectNode();

        objectNode.put("command", commandInput.getCommand());
        objectNode.put("timestamp", commandInput.getTimestamp());
        objectNode.put("result", objectMapper.valueToTree(result));

        return objectNode;
    }

    /**
     * GetOnlineUsers result
     *
     * @return                   the message generated by the execution of the input command
     */
    public static ArrayList<String> getOnlineUsersResult() {
        SingletonAdmin admin = SingletonAdmin.getInstance();

        ArrayList<String> onlineUsers = new ArrayList<>();

        for (User user: admin.getAllNormalUsers()) {
            if (user.isOnline()) {
                onlineUsers.add(user.getUsername());
            }
        }

        return onlineUsers;
    }
}
